/**
 * Merges dictionary fragments into the typed dictionary modules.
 *
 * - fragments/<feature>.en.json + fragments/<feature>.es.json (written by
 *   per-feature i18n migrations)
 * - validates: duplicate keys across fragments, keys missing in one language
 * - emits dictionaries/en.ts + dictionaries/es.ts
 *
 * Run from 1FRONT: node src/app/i18n/build-dicts.mjs
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const fragmentsDir = join(here, 'dictionaries', 'fragments');

const collect = (lang) => {
  const merged = {};
  const owners = {};
  const files = readdirSync(fragmentsDir)
    .filter((f) => f.endsWith(`.${lang}.json`))
    .sort();
  for (const file of files) {
    const data = JSON.parse(readFileSync(join(fragmentsDir, file), 'utf-8'));
    for (const [key, value] of Object.entries(data)) {
      if (merged[key] !== undefined) {
        throw new Error(`Duplicate key "${key}" in ${file} (already defined in ${owners[key]})`);
      }
      if (typeof value !== 'string') {
        throw new Error(`Key "${key}" in ${file} must map to a string`);
      }
      merged[key] = value;
      owners[key] = file;
    }
  }
  return merged;
};

const en = collect('en');
const es = collect('es');

const missingInEn = Object.keys(es).filter((k) => en[k] === undefined);
const missingInEs = Object.keys(en).filter((k) => es[k] === undefined);
if (missingInEn.length || missingInEs.length) {
  const fmt = (keys) => keys.slice(0, 10).map((k) => `  - ${k}`).join('\n');
  if (missingInEn.length) throw new Error(`Keys missing in .en.json:\n${fmt(missingInEn)}`);
  throw new Error(`Keys missing in .es.json:\n${fmt(missingInEs)}`);
}

const render = (name, dict, header) => `// AUTO-GENERATED by src/app/i18n/build-dicts.mjs — do not edit by hand.
// Edit fragments under src/app/i18n/dictionaries/fragments/ and re-run the script.
${header}
export const LANG_${name}: Record<string, string> = ${JSON.stringify(dict, null, 2)};
`;

writeFileSync(
  join(here, 'dictionaries', 'en.ts'),
  render('EN', en, "export type Lang = 'en' | 'es';"),
);
writeFileSync(
  join(here, 'dictionaries', 'es.ts'),
  render('ES', es, "import type { Lang } from './en';"),
);

console.log(`i18n dictionaries rebuilt: ${Object.keys(en).length} keys (en) / ${Object.keys(es).length} keys (es)`);
